// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package api

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/stashapp/stash_audio/internal/manager"
	"github.com/stashapp/stash_audio/internal/manager/config"
	"github.com/stashapp/stash_audio/pkg/models"
)

// Scraped Content is the forming union over the different scrapers
type ScrapedContent interface {
	IsScrapedContent()
}

type AddTempDLNAIPInput struct {
	Address string `json:"address"`
	// Duration to enable, in minutes. 0 or null for indefinite.
	Duration *int `json:"duration,omitempty"`
}

type AnonymiseDatabaseInput struct {
	Download *bool `json:"download,omitempty"`
}

type AssignAudioFileInput struct {
	AudioID string `json:"audio_id"`
	FileID  string `json:"file_id"`
}

type AudioCreateInput struct {
	Title        *string                `json:"title,omitempty"`
	Details      *string                `json:"details,omitempty"`
	Date         *string                `json:"date,omitempty"`
	Rating100    *int                   `json:"rating100,omitempty"`
	Organized    *bool                  `json:"organized,omitempty"`
	StudioID     *string                `json:"studio_id,omitempty"`
	TagIds       []string               `json:"tag_ids,omitempty"`
	PerformerIds []string               `json:"performer_ids,omitempty"`
	GroupIds     []string               `json:"group_ids,omitempty"`
	Urls         []string               `json:"urls,omitempty"`
	StashIds     []*models.StashIDInput `json:"stash_ids,omitempty"`
	CoverImage   *string                `json:"cover_image,omitempty"`
	FileIds      []string               `json:"file_ids,omitempty"`
}

type AudioPathsType struct {
	Cover     *string `json:"cover,omitempty"`
	Stream    *string `json:"stream,omitempty"`
	Vtt       *string `json:"vtt,omitempty"`
	Funscript *string `json:"funscript,omitempty"`
	Subtitles *string `json:"subtitles,omitempty"`
}

type AudioUpdateInput struct {
	ClientMutationID *string                `json:"clientMutationId,omitempty"`
	ID               string                 `json:"id"`
	Title            *string                `json:"title,omitempty"`
	Details          *string                `json:"details,omitempty"`
	Date             *string                `json:"date,omitempty"`
	Rating100        *int                   `json:"rating100,omitempty"`
	Organized        *bool                  `json:"organized,omitempty"`
	StudioID         *string                `json:"studio_id,omitempty"`
	TagIds           []string               `json:"tag_ids,omitempty"`
	PerformerIds     []string               `json:"performer_ids,omitempty"`
	GroupIds         []string               `json:"group_ids,omitempty"`
	Urls             []string               `json:"urls,omitempty"`
	StashIds         []*models.StashIDInput `json:"stash_ids,omitempty"`
	CoverImage       *string                `json:"cover_image,omitempty"`
	PrimaryFileID    *string                `json:"primary_file_id,omitempty"`
}

type AudiosDestroyInput struct {
	Ids             []string `json:"ids"`
	DeleteFile      *bool    `json:"delete_file,omitempty"`
	DeleteGenerated *bool    `json:"delete_generated,omitempty"`
}

type BackupDatabaseInput struct {
	Download *bool `json:"download,omitempty"`
	// If true, blob files will be included in the backup. This can significantly increase the size of the backup and the time it takes to create it, but allows for a complete backup of the system that can be restored without needing access to the original media files.
	IncludeBlobs *bool `json:"includeBlobs,omitempty"`
}

type BulkAudioUpdateInput struct {
	ClientMutationID *string            `json:"clientMutationId,omitempty"`
	Ids              []string           `json:"ids,omitempty"`
	Title            *string            `json:"title,omitempty"`
	Details          *string            `json:"details,omitempty"`
	Date             *string            `json:"date,omitempty"`
	Rating100        *int               `json:"rating100,omitempty"`
	Organized        *bool              `json:"organized,omitempty"`
	StudioID         *string            `json:"studio_id,omitempty"`
	TagIds           *BulkUpdateIds     `json:"tag_ids,omitempty"`
	PerformerIds     *BulkUpdateIds     `json:"performer_ids,omitempty"`
	Urls             *BulkUpdateStrings `json:"urls,omitempty"`
}

type BulkGroupUpdateInput struct {
	ClientMutationID *string                           `json:"clientMutationId,omitempty"`
	Ids              []string                          `json:"ids,omitempty"`
	Rating100        *int                              `json:"rating100,omitempty"`
	Date             *string                           `json:"date,omitempty"`
	Synopsis         *string                           `json:"synopsis,omitempty"`
	StudioID         *string                           `json:"studio_id,omitempty"`
	Director         *string                           `json:"director,omitempty"`
	Urls             *BulkUpdateStrings                `json:"urls,omitempty"`
	TagIds           *BulkUpdateIds                    `json:"tag_ids,omitempty"`
	ContainingGroups *BulkUpdateGroupDescriptionsInput `json:"containing_groups,omitempty"`
	SubGroups        *BulkUpdateGroupDescriptionsInput `json:"sub_groups,omitempty"`
	CustomFields     *models.CustomFieldsInput         `json:"custom_fields,omitempty"`
}

type BulkMovieUpdateInput struct {
	ClientMutationID *string            `json:"clientMutationId,omitempty"`
	Ids              []string           `json:"ids,omitempty"`
	Rating100        *int               `json:"rating100,omitempty"`
	StudioID         *string            `json:"studio_id,omitempty"`
	Director         *string            `json:"director,omitempty"`
	Urls             *BulkUpdateStrings `json:"urls,omitempty"`
	TagIds           *BulkUpdateIds     `json:"tag_ids,omitempty"`
}

type BulkPerformerUpdateInput struct {
	ClientMutationID *string                `json:"clientMutationId,omitempty"`
	Ids              []string               `json:"ids,omitempty"`
	Disambiguation   *string                `json:"disambiguation,omitempty"`
	URL              *string                `json:"url,omitempty"`
	Urls             *BulkUpdateStrings     `json:"urls,omitempty"`
	Gender           *models.GenderEnum     `json:"gender,omitempty"`
	Birthdate        *string                `json:"birthdate,omitempty"`
	Ethnicity        *string                `json:"ethnicity,omitempty"`
	Country          *string                `json:"country,omitempty"`
	EyeColor         *string                `json:"eye_color,omitempty"`
	HeightCm         *int                   `json:"height_cm,omitempty"`
	Measurements     *string                `json:"measurements,omitempty"`
	FakeTits         *string                `json:"fake_tits,omitempty"`
	PenisLength      *float64               `json:"penis_length,omitempty"`
	Circumcised      *models.CircumisedEnum `json:"circumcised,omitempty"`
	CareerLength     *string                `json:"career_length,omitempty"`
	CareerStart      *int                   `json:"career_start,omitempty"`
	CareerEnd        *int                   `json:"career_end,omitempty"`
	Tattoos          *string                `json:"tattoos,omitempty"`
	Piercings        *string                `json:"piercings,omitempty"`
	// Duplicate aliases and those equal to name will result in an error (case-insensitive)
	AliasList     *BulkUpdateStrings        `json:"alias_list,omitempty"`
	Twitter       *string                   `json:"twitter,omitempty"`
	Instagram     *string                   `json:"instagram,omitempty"`
	Favorite      *bool                     `json:"favorite,omitempty"`
	TagIds        *BulkUpdateIds            `json:"tag_ids,omitempty"`
	Rating100     *int                      `json:"rating100,omitempty"`
	Details       *string                   `json:"details,omitempty"`
	DeathDate     *string                   `json:"death_date,omitempty"`
	HairColor     *string                   `json:"hair_color,omitempty"`
	Weight        *int                      `json:"weight,omitempty"`
	IgnoreAutoTag *bool                     `json:"ignore_auto_tag,omitempty"`
	CustomFields  *models.CustomFieldsInput `json:"custom_fields,omitempty"`
}

type BulkStudioUpdateInput struct {
	Ids           []string           `json:"ids"`
	URL           *string            `json:"url,omitempty"`
	Urls          *BulkUpdateStrings `json:"urls,omitempty"`
	ParentID      *string            `json:"parent_id,omitempty"`
	Rating100     *int               `json:"rating100,omitempty"`
	Favorite      *bool              `json:"favorite,omitempty"`
	Details       *string            `json:"details,omitempty"`
	TagIds        *BulkUpdateIds     `json:"tag_ids,omitempty"`
	IgnoreAutoTag *bool              `json:"ignore_auto_tag,omitempty"`
	Organized     *bool              `json:"organized,omitempty"`
}

type BulkTagUpdateInput struct {
	Ids         []string `json:"ids,omitempty"`
	Description *string  `json:"description,omitempty"`
	// Duplicate aliases and those equal to name will result in an error (case-insensitive)
	Aliases       *BulkUpdateStrings `json:"aliases,omitempty"`
	IgnoreAutoTag *bool              `json:"ignore_auto_tag,omitempty"`
	Favorite      *bool              `json:"favorite,omitempty"`
	ParentIds     *BulkUpdateIds     `json:"parent_ids,omitempty"`
	ChildIds      *BulkUpdateIds     `json:"child_ids,omitempty"`
}

type BulkUpdateGroupDescriptionsInput struct {
	Groups []*GroupDescriptionInput      `json:"groups"`
	Mode   models.RelationshipUpdateMode `json:"mode"`
}

type BulkUpdateIds struct {
	Ids  []string                      `json:"ids,omitempty"`
	Mode models.RelationshipUpdateMode `json:"mode"`
}

type BulkUpdateStrings struct {
	Values []string                      `json:"values,omitempty"`
	Mode   models.RelationshipUpdateMode `json:"mode"`
}

type ConfigDLNAInput struct {
	ServerName *string `json:"serverName,omitempty"`
	// True if DLNA service should be enabled by default
	Enabled *bool `json:"enabled,omitempty"`
	// Defaults to 1338
	Port *int `json:"port,omitempty"`
	// List of IPs whitelisted for DLNA service
	WhitelistedIPs []string `json:"whitelistedIPs,omitempty"`
	// List of interfaces to run DLNA on. Empty for all
	Interfaces []string `json:"interfaces,omitempty"`
	// Order to sort videos
	VideoSortOrder *string `json:"videoSortOrder,omitempty"`
}

type ConfigDLNAResult struct {
	ServerName string `json:"serverName"`
	// True if DLNA service should be enabled by default
	Enabled bool `json:"enabled"`
	// Defaults to 1338
	Port int `json:"port"`
	// List of IPs whitelisted for DLNA service
	WhitelistedIPs []string `json:"whitelistedIPs"`
	// List of interfaces to run DLNA on. Empty for all
	Interfaces []string `json:"interfaces"`
	// Order to sort videos
	VideoSortOrder string `json:"videoSortOrder"`
}

type ConfigDefaultSettingsInput struct {
	Scan     *manager.ScanMetadataInput    `json:"scan,omitempty"`
	Identify *IdentifyMetadataInput        `json:"identify,omitempty"`
	AutoTag  *manager.AutoTagMetadataInput `json:"autoTag,omitempty"`
	Generate *GenerateMetadataInput        `json:"generate,omitempty"`
	// If true, delete file checkbox will be checked by default
	DeleteFile *bool `json:"deleteFile,omitempty"`
	// If true, delete generated files checkbox will be checked by default
	DeleteGenerated *bool `json:"deleteGenerated,omitempty"`
}

type ConfigDefaultSettingsResult struct {
	Scan     *config.ScanMetadataOptions     `json:"scan,omitempty"`
	Identify *IdentifyMetadataTaskOptions    `json:"identify,omitempty"`
	AutoTag  *config.AutoTagMetadataOptions  `json:"autoTag,omitempty"`
	Generate *models.GenerateMetadataOptions `json:"generate,omitempty"`
	// If true, delete file checkbox will be checked by default
	DeleteFile *bool `json:"deleteFile,omitempty"`
	// If true, delete generated supporting files checkbox will be checked by default
	DeleteGenerated *bool `json:"deleteGenerated,omitempty"`
}

type ConfigDisableDropdownCreateInput struct {
	Performer *bool `json:"performer,omitempty"`
	Tag       *bool `json:"tag,omitempty"`
	Studio    *bool `json:"studio,omitempty"`
	Movie     *bool `json:"movie,omitempty"`
	Gallery   *bool `json:"gallery,omitempty"`
}

type ConfigGeneralInput struct {
	// Array of file paths to content
	Stashes []*config.StashConfigInput `json:"stashes,omitempty"`
	// Path to the SQLite database
	DatabasePath *string `json:"databasePath,omitempty"`
	// Path to backup directory
	BackupDirectoryPath *string `json:"backupDirectoryPath,omitempty"`
	// Path to trash directory - if set, deleted files will be moved here instead of being permanently deleted
	DeleteTrashPath *string `json:"deleteTrashPath,omitempty"`
	// Path to generated files
	GeneratedPath *string `json:"generatedPath,omitempty"`
	// Path to import/export files
	MetadataPath *string `json:"metadataPath,omitempty"`
	// Path to scrapers
	ScrapersPath *string `json:"scrapersPath,omitempty"`
	// Path to plugins
	PluginsPath *string `json:"pluginsPath,omitempty"`
	// Path to cache
	CachePath *string `json:"cachePath,omitempty"`
	// Path to blobs - required for filesystem blob storage
	BlobsPath *string `json:"blobsPath,omitempty"`
	// Where to store blobs
	BlobsStorage *config.BlobsStorageType `json:"blobsStorage,omitempty"`
	// Path to the ffmpeg binary. If empty, stash will attempt to find it in the path or config directory
	FfmpegPath *string `json:"ffmpegPath,omitempty"`
	// Path to the ffprobe binary. If empty, stash will attempt to find it in the path or config directory
	FfprobePath *string `json:"ffprobePath,omitempty"`
	// Whether to calculate MD5 checksums for scene video files
	CalculateMd5 *bool `json:"calculateMD5,omitempty"`
	// Hash algorithm to use for generated file naming
	VideoFileNamingAlgorithm *models.HashAlgorithm `json:"videoFileNamingAlgorithm,omitempty"`
	// Number of parallel tasks to start during scan/generate
	ParallelTasks *int `json:"parallelTasks,omitempty"`
	// Include audio stream in previews
	PreviewAudio *bool `json:"previewAudio,omitempty"`
	// Number of segments in a preview file
	PreviewSegments *int `json:"previewSegments,omitempty"`
	// Preview segment duration, in seconds
	PreviewSegmentDuration *float64 `json:"previewSegmentDuration,omitempty"`
	// Duration of start of video to exclude when generating previews
	PreviewExcludeStart *string `json:"previewExcludeStart,omitempty"`
	// Duration of end of video to exclude when generating previews
	PreviewExcludeEnd *string `json:"previewExcludeEnd,omitempty"`
	// Preset when generating preview
	PreviewPreset *models.PreviewPreset `json:"previewPreset,omitempty"`
	// Transcode Hardware Acceleration
	TranscodeHardwareAcceleration *bool `json:"transcodeHardwareAcceleration,omitempty"`
	// Max generated transcode size
	MaxTranscodeSize *models.StreamingResolutionEnum `json:"maxTranscodeSize,omitempty"`
	// Max streaming transcode size
	MaxStreamingTranscodeSize *models.StreamingResolutionEnum `json:"maxStreamingTranscodeSize,omitempty"`
	// ffmpeg transcode input args - injected before input file
	// These are applied to generated transcodes (previews and transcodes)
	TranscodeInputArgs []string `json:"transcodeInputArgs,omitempty"`
	// ffmpeg transcode output args - injected before output file
	// These are applied to generated transcodes (previews and transcodes)
	TranscodeOutputArgs []string `json:"transcodeOutputArgs,omitempty"`
	// ffmpeg stream input args - injected before input file
	// These are applied when live transcoding
	LiveTranscodeInputArgs []string `json:"liveTranscodeInputArgs,omitempty"`
	// ffmpeg stream output args - injected before output file
	// These are applied when live transcoding
	LiveTranscodeOutputArgs []string `json:"liveTranscodeOutputArgs,omitempty"`
	// whether to include range in generated funscript heatmaps
	DrawFunscriptHeatmapRange *bool `json:"drawFunscriptHeatmapRange,omitempty"`
	// Write image thumbnails to disk when generating on the fly
	WriteImageThumbnails *bool `json:"writeImageThumbnails,omitempty"`
	// Create Image Clips from Video extensions when Videos are disabled in Library
	CreateImageClipsFromVideos *bool `json:"createImageClipsFromVideos,omitempty"`
	// Username
	Username *string `json:"username,omitempty"`
	// Password
	Password *string `json:"password,omitempty"`
	// Maximum session cookie age
	MaxSessionAge *int `json:"maxSessionAge,omitempty"`
	// Name of the log file
	LogFile *string `json:"logFile,omitempty"`
	// Whether to also output to stderr
	LogOut *bool `json:"logOut,omitempty"`
	// Minimum log level
	LogLevel *string `json:"logLevel,omitempty"`
	// Whether to log http access
	LogAccess *bool `json:"logAccess,omitempty"`
	// Maximum log size
	LogFileMaxSize *int `json:"logFileMaxSize,omitempty"`
	// True if galleries should be created from folders with images
	CreateGalleriesFromFolders *bool `json:"createGalleriesFromFolders,omitempty"`
	// Regex used to identify images as gallery covers
	GalleryCoverRegex *string `json:"galleryCoverRegex,omitempty"`
	// Array of video file extensions
	VideoExtensions []string `json:"videoExtensions,omitempty"`
	// Array of image file extensions
	ImageExtensions []string `json:"imageExtensions,omitempty"`
	// Array of gallery zip file extensions
	GalleryExtensions []string `json:"galleryExtensions,omitempty"`
	// Array of file regexp to exclude from Video Scans
	Excludes []string `json:"excludes,omitempty"`
	// Array of file regexp to exclude from Image Scans
	ImageExcludes []string `json:"imageExcludes,omitempty"`
	// Array of audio file extensions
	AudioExtensions []string `json:"audioExtensions,omitempty"`
	// Array of file regexp to exclude from Audio Scans
	AudioExcludes []string `json:"audioExcludes,omitempty"`
	// Custom Performer Image Location
	CustomPerformerImageLocation *string `json:"customPerformerImageLocation,omitempty"`
	// Stash-box instances used for tagging
	StashBoxes []*config.StashBoxInput `json:"stashBoxes,omitempty"`
	// Python path - resolved using path if unset
	PythonPath *string `json:"pythonPath,omitempty"`
	// Source of scraper packages
	ScraperPackageSources []*PackageSourceInput `json:"scraperPackageSources,omitempty"`
	// Source of plugin packages
	PluginPackageSources []*PackageSourceInput `json:"pluginPackageSources,omitempty"`
	// Size of the longest dimension for each sprite in pixels
	SpriteScreenshotSize *int `json:"spriteScreenshotSize,omitempty"`
	// True if sprite generation should use the sprite interval and min/max sprites settings instead of the default
	UseCustomSpriteInterval *bool `json:"useCustomSpriteInterval,omitempty"`
	// Time between two different scrubber sprites in seconds - only used if useCustomSpriteInterval is true
	SpriteInterval *float64 `json:"spriteInterval,omitempty"`
	// Minimum number of sprites to be generated - only used if useCustomSpriteInterval is true
	MinimumSprites *int `json:"minimumSprites,omitempty"`
	// Minimum number of sprites to be generated - only used if useCustomSpriteInterval is true
	MaximumSprites *int `json:"maximumSprites,omitempty"`
}

type ConfigGeneralResult struct {
	// Array of file paths to content
	Stashes []*config.StashConfig `json:"stashes"`
	// Path to the SQLite database
	DatabasePath string `json:"databasePath"`
	// Path to backup directory
	BackupDirectoryPath string `json:"backupDirectoryPath"`
	// Path to trash directory - if set, deleted files will be moved here instead of being permanently deleted
	DeleteTrashPath string `json:"deleteTrashPath"`
	// Path to generated files
	GeneratedPath string `json:"generatedPath"`
	// Path to import/export files
	MetadataPath string `json:"metadataPath"`
	// Path to the config file used
	ConfigFilePath string `json:"configFilePath"`
	// Path to scrapers
	ScrapersPath string `json:"scrapersPath"`
	// Path to plugins
	PluginsPath string `json:"pluginsPath"`
	// Path to cache
	CachePath string `json:"cachePath"`
	// Path to blobs - required for filesystem blob storage
	BlobsPath string `json:"blobsPath"`
	// Where to store blobs
	BlobsStorage config.BlobsStorageType `json:"blobsStorage"`
	// Path to the ffmpeg binary. If empty, stash will attempt to find it in the path or config directory
	FfmpegPath string `json:"ffmpegPath"`
	// Path to the ffprobe binary. If empty, stash will attempt to find it in the path or config directory
	FfprobePath string `json:"ffprobePath"`
	// Whether to calculate MD5 checksums for scene video files
	CalculateMd5 bool `json:"calculateMD5"`
	// Hash algorithm to use for generated file naming
	VideoFileNamingAlgorithm models.HashAlgorithm `json:"videoFileNamingAlgorithm"`
	// Number of parallel tasks to start during scan/generate
	ParallelTasks int `json:"parallelTasks"`
	// Include audio stream in previews
	PreviewAudio bool `json:"previewAudio"`
	// Number of segments in a preview file
	PreviewSegments int `json:"previewSegments"`
	// Preview segment duration, in seconds
	PreviewSegmentDuration float64 `json:"previewSegmentDuration"`
	// Duration of start of video to exclude when generating previews
	PreviewExcludeStart string `json:"previewExcludeStart"`
	// Duration of end of video to exclude when generating previews
	PreviewExcludeEnd string `json:"previewExcludeEnd"`
	// Preset when generating preview
	PreviewPreset models.PreviewPreset `json:"previewPreset"`
	// Transcode Hardware Acceleration
	TranscodeHardwareAcceleration bool `json:"transcodeHardwareAcceleration"`
	// Max generated transcode size
	MaxTranscodeSize *models.StreamingResolutionEnum `json:"maxTranscodeSize,omitempty"`
	// Max streaming transcode size
	MaxStreamingTranscodeSize *models.StreamingResolutionEnum `json:"maxStreamingTranscodeSize,omitempty"`
	// ffmpeg transcode input args - injected before input file
	// These are applied to generated transcodes (previews and transcodes)
	TranscodeInputArgs []string `json:"transcodeInputArgs"`
	// ffmpeg transcode output args - injected before output file
	// These are applied to generated transcodes (previews and transcodes)
	TranscodeOutputArgs []string `json:"transcodeOutputArgs"`
	// ffmpeg stream input args - injected before input file
	// These are applied when live transcoding
	LiveTranscodeInputArgs []string `json:"liveTranscodeInputArgs"`
	// ffmpeg stream output args - injected before output file
	// These are applied when live transcoding
	LiveTranscodeOutputArgs []string `json:"liveTranscodeOutputArgs"`
	// whether to include range in generated funscript heatmaps
	DrawFunscriptHeatmapRange bool `json:"drawFunscriptHeatmapRange"`
	// Write image thumbnails to disk when generating on the fly
	WriteImageThumbnails bool `json:"writeImageThumbnails"`
	// Create Image Clips from Video extensions when Videos are disabled in Library
	CreateImageClipsFromVideos bool `json:"createImageClipsFromVideos"`
	// API Key
	APIKey string `json:"apiKey"`
	// Username
	Username string `json:"username"`
	// Password
	Password string `json:"password"`
	// Maximum session cookie age
	MaxSessionAge int `json:"maxSessionAge"`
	// Name of the log file
	LogFile *string `json:"logFile,omitempty"`
	// Whether to also output to stderr
	LogOut bool `json:"logOut"`
	// Minimum log level
	LogLevel string `json:"logLevel"`
	// Whether to log http access
	LogAccess bool `json:"logAccess"`
	// Maximum log size
	LogFileMaxSize int `json:"logFileMaxSize"`
	// True if sprite generation should use the sprite interval and min/max sprites settings instead of the default
	UseCustomSpriteInterval bool `json:"useCustomSpriteInterval"`
	// Time between two different scrubber sprites in seconds - only used if useCustomSpriteInterval is true
	SpriteInterval float64 `json:"spriteInterval"`
	// Minimum number of sprites to be generated - only used if useCustomSpriteInterval is true
	MinimumSprites int `json:"minimumSprites"`
	// Maximum number of sprites to be generated - only used if useCustomSpriteInterval is true
	MaximumSprites int `json:"maximumSprites"`
	// Size of the longest dimension for each sprite in pixels
	SpriteScreenshotSize int `json:"spriteScreenshotSize"`
	// Array of video file extensions
	VideoExtensions []string `json:"videoExtensions"`
	// Array of image file extensions
	ImageExtensions []string `json:"imageExtensions"`
	// Array of gallery zip file extensions
	GalleryExtensions []string `json:"galleryExtensions"`
	// True if galleries should be created from folders with images
	CreateGalleriesFromFolders bool `json:"createGalleriesFromFolders"`
	// Regex used to identify images as gallery covers
	GalleryCoverRegex string `json:"galleryCoverRegex"`
	// Array of file regexp to exclude from Video Scans
	Excludes []string `json:"excludes"`
	// Array of file regexp to exclude from Image Scans
	ImageExcludes []string `json:"imageExcludes"`
	// Array of audio file extensions
	AudioExtensions []string `json:"audioExtensions"`
	// Array of file regexp to exclude from Audio Scans
	AudioExcludes []string `json:"audioExcludes"`
	// Custom Performer Image Location
	CustomPerformerImageLocation *string `json:"customPerformerImageLocation,omitempty"`
	// Stash-box instances used for tagging
	StashBoxes []*models.StashBox `json:"stashBoxes"`
	// Python path - resolved using path if unset
	PythonPath string `json:"pythonPath"`
	// Source of scraper packages
	ScraperPackageSources []*models.PackageSource `json:"scraperPackageSources"`
	// Source of plugin packages
	PluginPackageSources []*models.PackageSource `json:"pluginPackageSources"`
}

type ConfigImageLightboxInput struct {
	SlideshowDelay             *int                             `json:"slideshowDelay,omitempty"`
	DisplayMode                *config.ImageLightboxDisplayMode `json:"displayMode,omitempty"`
	ScaleUp                    *bool                            `json:"scaleUp,omitempty"`
	ResetZoomOnNav             *bool                            `json:"resetZoomOnNav,omitempty"`
	ScrollMode                 *config.ImageLightboxScrollMode  `json:"scrollMode,omitempty"`
	ScrollAttemptsBeforeChange *int                             `json:"scrollAttemptsBeforeChange,omitempty"`
	DisableAnimation           *bool                            `json:"disableAnimation,omitempty"`
}

type ConfigInterfaceInput struct {
	// True if SFW content mode is enabled
	SfwContentMode *bool `json:"sfwContentMode,omitempty"`
	// Ordered list of items that should be shown in the menu
	MenuItems []string `json:"menuItems,omitempty"`
	// Enable sound on mouseover previews
	SoundOnPreview *bool `json:"soundOnPreview,omitempty"`
	// Show title and tags in wall view
	WallShowTitle *bool `json:"wallShowTitle,omitempty"`
	// Wall playback type
	WallPlayback *string `json:"wallPlayback,omitempty"`
	// Show scene scrubber by default
	ShowScrubber *bool `json:"showScrubber,omitempty"`
	// Maximum duration (in seconds) in which a scene video will loop in the scene player
	MaximumLoopDuration *int `json:"maximumLoopDuration,omitempty"`
	// If true, video will autostart on load in the scene player
	AutostartVideo *bool `json:"autostartVideo,omitempty"`
	// If true, video will autostart when loading from play random or play selected
	AutostartVideoOnPlaySelected *bool `json:"autostartVideoOnPlaySelected,omitempty"`
	// If true, next scene in playlist will be played at video end by default
	ContinuePlaylistDefault *bool `json:"continuePlaylistDefault,omitempty"`
	// If true, studio overlays will be shown as text instead of logo images
	ShowStudioAsText *bool `json:"showStudioAsText,omitempty"`
	// Custom CSS
	CSS        *string `json:"css,omitempty"`
	CSSEnabled *bool   `json:"cssEnabled,omitempty"`
	// Custom Javascript
	Javascript        *string `json:"javascript,omitempty"`
	JavascriptEnabled *bool   `json:"javascriptEnabled,omitempty"`
	// Custom Locales
	CustomLocales        *string `json:"customLocales,omitempty"`
	CustomLocalesEnabled *bool   `json:"customLocalesEnabled,omitempty"`
	// When true, disables all customizations (plugins, CSS, JavaScript, locales) for troubleshooting
	DisableCustomizations *bool `json:"disableCustomizations,omitempty"`
	// Interface language
	Language      *string                   `json:"language,omitempty"`
	ImageLightbox *ConfigImageLightboxInput `json:"imageLightbox,omitempty"`
	// Set to true to disable creating new objects via the dropdown menus
	DisableDropdownCreate *ConfigDisableDropdownCreateInput `json:"disableDropdownCreate,omitempty"`
	// Handy Connection Key
	HandyKey *string `json:"handyKey,omitempty"`
	// Funscript Time Offset
	FunscriptOffset *int `json:"funscriptOffset,omitempty"`
	// Whether to use Stash Hosted Funscript
	UseStashHostedFunscript *bool `json:"useStashHostedFunscript,omitempty"`
	// True if we should not auto-open a browser window on startup
	NoBrowser *bool `json:"noBrowser,omitempty"`
	// True if we should send notifications to the desktop
	NotificationsEnabled *bool `json:"notificationsEnabled,omitempty"`
}

type ConfigInterfaceResult struct {
	// True if SFW content mode is enabled
	SfwContentMode bool `json:"sfwContentMode"`
	// Ordered list of items that should be shown in the menu
	MenuItems []string `json:"menuItems,omitempty"`
	// Enable sound on mouseover previews
	SoundOnPreview *bool `json:"soundOnPreview,omitempty"`
	// Show title and tags in wall view
	WallShowTitle *bool `json:"wallShowTitle,omitempty"`
	// Wall playback type
	WallPlayback *string `json:"wallPlayback,omitempty"`
	// Show scene scrubber by default
	ShowScrubber *bool `json:"showScrubber,omitempty"`
	// Maximum duration (in seconds) in which a scene video will loop in the scene player
	MaximumLoopDuration *int `json:"maximumLoopDuration,omitempty"`
	// True if we should not auto-open a browser window on startup
	NoBrowser *bool `json:"noBrowser,omitempty"`
	// True if we should send desktop notifications
	NotificationsEnabled *bool `json:"notificationsEnabled,omitempty"`
	// If true, video will autostart on load in the scene player
	AutostartVideo *bool `json:"autostartVideo,omitempty"`
	// If true, video will autostart when loading from play random or play selected
	AutostartVideoOnPlaySelected *bool `json:"autostartVideoOnPlaySelected,omitempty"`
	// If true, next scene in playlist will be played at video end by default
	ContinuePlaylistDefault *bool `json:"continuePlaylistDefault,omitempty"`
	// If true, studio overlays will be shown as text instead of logo images
	ShowStudioAsText *bool `json:"showStudioAsText,omitempty"`
	// Custom CSS
	CSS        *string `json:"css,omitempty"`
	CSSEnabled *bool   `json:"cssEnabled,omitempty"`
	// Custom Javascript
	Javascript        *string `json:"javascript,omitempty"`
	JavascriptEnabled *bool   `json:"javascriptEnabled,omitempty"`
	// Custom Locales
	CustomLocales        *string `json:"customLocales,omitempty"`
	CustomLocalesEnabled *bool   `json:"customLocalesEnabled,omitempty"`
	// When true, disables all customizations (plugins, CSS, JavaScript, locales) for troubleshooting
	DisableCustomizations *bool `json:"disableCustomizations,omitempty"`
	// Interface language
	Language      *string                           `json:"language,omitempty"`
	ImageLightbox *config.ConfigImageLightboxResult `json:"imageLightbox"`
	// Fields are true if creating via dropdown menus are disabled
	DisableDropdownCreate *config.ConfigDisableDropdownCreate `json:"disableDropdownCreate"`
	// Handy Connection Key
	HandyKey *string `json:"handyKey,omitempty"`
	// Funscript Time Offset
	FunscriptOffset *int `json:"funscriptOffset,omitempty"`
	// Whether to use Stash Hosted Funscript
	UseStashHostedFunscript *bool `json:"useStashHostedFunscript,omitempty"`
}

// All configuration settings
type ConfigResult struct {
	General   *ConfigGeneralResult              `json:"general"`
	Interface *ConfigInterfaceResult            `json:"interface"`
	Dlna      *ConfigDLNAResult                 `json:"dlna"`
	Scraping  *ConfigScrapingResult             `json:"scraping"`
	Defaults  *ConfigDefaultSettingsResult      `json:"defaults"`
	UI        map[string]any                    `json:"ui"`
	Plugins   map[string]map[string]interface{} `json:"plugins"`
}

type ConfigScrapingInput struct {
	// Scraper user agent string
	ScraperUserAgent *string `json:"scraperUserAgent,omitempty"`
	// Scraper CDP path. Path to chrome executable or remote address
	ScraperCDPPath *string `json:"scraperCDPPath,omitempty"`
	// Whether the scraper should check for invalid certificates
	ScraperCertCheck *bool `json:"scraperCertCheck,omitempty"`
	// Tags blacklist during scraping
	ExcludeTagPatterns []string `json:"excludeTagPatterns,omitempty"`
}

type ConfigScrapingResult struct {
	// Scraper user agent string
	ScraperUserAgent *string `json:"scraperUserAgent,omitempty"`
	// Scraper CDP path. Path to chrome executable or remote address
	ScraperCDPPath *string `json:"scraperCDPPath,omitempty"`
	// Whether the scraper should check for invalid certificates
	ScraperCertCheck bool `json:"scraperCertCheck"`
	// Tags blacklist during scraping
	ExcludeTagPatterns []string `json:"excludeTagPatterns"`
}

type Dlnaip struct {
	IPAddress string `json:"ipAddress"`
	// Time until IP will be no longer allowed/disallowed
	Until *time.Time `json:"until,omitempty"`
}

type DLNAStatus struct {
	Running bool `json:"running"`
	// If not currently running, time until it will be started. If running, time until it will be stopped
	Until              *time.Time `json:"until,omitempty"`
	RecentIPAddresses  []string   `json:"recentIPAddresses"`
	AllowedIPAddresses []*Dlnaip  `json:"allowedIPAddresses"`
}

type DestroyFilterInput struct {
	ID string `json:"id"`
}

// Directory structure of a path
type Directory struct {
	Path        string   `json:"path"`
	Parent      *string  `json:"parent,omitempty"`
	Directories []string `json:"directories"`
}

type DisableDLNAInput struct {
	// Duration to enable, in minutes. 0 or null for indefinite.
	Duration *int `json:"duration,omitempty"`
}

type EnableDLNAInput struct {
	// Duration to enable, in minutes. 0 or null for indefinite.
	Duration *int `json:"duration,omitempty"`
}

type FileDuplicationCriterionInput struct {
	Duplicated *bool `json:"duplicated,omitempty"`
	// Currently unimplemented. Intended for phash distance matching.
	Distance *int `json:"distance,omitempty"`
	// Filter by phash duplication
	Phash *bool `json:"phash,omitempty"`
}

type FileSetFingerprintsInput struct {
	ID string `json:"id"`
	// only supplied fingerprint types will be modified
	Fingerprints []*SetFingerprintsInput `json:"fingerprints"`
}

type FindAudiosResultType struct {
	Count int `json:"count"`
	// Total duration in seconds
	Duration float64 `json:"duration"`
	// Total file size in bytes
	Filesize float64         `json:"filesize"`
	Audios   []*models.Audio `json:"audios"`
}

type FindFilesResultType struct {
	Count int `json:"count"`
	// Total megapixels of any image files
	Megapixels float64 `json:"megapixels"`
	// Total duration in seconds of any video files
	Duration float64 `json:"duration"`
	// Total file size in bytes
	Size  int        `json:"size"`
	Files []BaseFile `json:"files"`
}

type FindFoldersResultType struct {
	Count   int              `json:"count"`
	Folders []*models.Folder `json:"folders"`
}

type FindGroupsResultType struct {
	Count  int             `json:"count"`
	Groups []*models.Group `json:"groups"`
}

type FindJobInput struct {
	ID string `json:"id"`
}

type FindMoviesResultType struct {
	Count  int             `json:"count"`
	Movies []*models.Group `json:"movies"`
}

type FindPerformersResultType struct {
	Count      int                 `json:"count"`
	Performers []*models.Performer `json:"performers"`
}

type FindStudiosResultType struct {
	Count   int              `json:"count"`
	Studios []*models.Studio `json:"studios"`
}

type FindTagsResultType struct {
	Count int           `json:"count"`
	Tags  []*models.Tag `json:"tags"`
}

type GenerateAPIKeyInput struct {
	Clear *bool `json:"clear,omitempty"`
}

type GenerateMetadataInput struct {
	Covers              *bool                        `json:"covers,omitempty"`
	Sprites             *bool                        `json:"sprites,omitempty"`
	Previews            *bool                        `json:"previews,omitempty"`
	ImagePreviews       *bool                        `json:"imagePreviews,omitempty"`
	PreviewOptions      *GeneratePreviewOptionsInput `json:"previewOptions,omitempty"`
	Markers             *bool                        `json:"markers,omitempty"`
	MarkerImagePreviews *bool                        `json:"markerImagePreviews,omitempty"`
	MarkerScreenshots   *bool                        `json:"markerScreenshots,omitempty"`
	Transcodes          *bool                        `json:"transcodes,omitempty"`
	// Generate transcodes even if not required
	ForceTranscodes *bool `json:"forceTranscodes,omitempty"`
	// Generate video phashes during scan
	Phashes                   *bool `json:"phashes,omitempty"`
	InteractiveHeatmapsSpeeds *bool `json:"interactiveHeatmapsSpeeds,omitempty"`
	// Generate image phashes during scan
	ImagePhashes    *bool `json:"imagePhashes,omitempty"`
	ImageThumbnails *bool `json:"imageThumbnails,omitempty"`
	ClipPreviews    *bool `json:"clipPreviews,omitempty"`
	// scene ids to generate for
	SceneIDs []string `json:"sceneIDs,omitempty"`
	// marker ids to generate for
	MarkerIDs []string `json:"markerIDs,omitempty"`
	// image ids to generate for
	ImageIDs []string `json:"imageIDs,omitempty"`
	// gallery ids to generate for
	GalleryIDs []string `json:"galleryIDs,omitempty"`
	// paths to run generate on, in addition to the other ID lists
	Paths []string `json:"paths,omitempty"`
	// overwrite existing media
	Overwrite *bool `json:"overwrite,omitempty"`
}

type GeneratePreviewOptionsInput struct {
	// Number of segments in a preview file
	PreviewSegments *int `json:"previewSegments,omitempty"`
	// Preview segment duration, in seconds
	PreviewSegmentDuration *float64 `json:"previewSegmentDuration,omitempty"`
	// Duration of start of video to exclude when generating previews
	PreviewExcludeStart *string `json:"previewExcludeStart,omitempty"`
	// Duration of end of video to exclude when generating previews
	PreviewExcludeEnd *string `json:"previewExcludeEnd,omitempty"`
	// Preset when generating preview
	PreviewPreset *models.PreviewPreset `json:"previewPreset,omitempty"`
}

type GroupCreateInput struct {
	Name    string  `json:"name"`
	Aliases *string `json:"aliases,omitempty"`
	// Duration in seconds
	Duration         *int                     `json:"duration,omitempty"`
	Date             *string                  `json:"date,omitempty"`
	Rating100        *int                     `json:"rating100,omitempty"`
	StudioID         *string                  `json:"studio_id,omitempty"`
	Director         *string                  `json:"director,omitempty"`
	Synopsis         *string                  `json:"synopsis,omitempty"`
	Urls             []string                 `json:"urls,omitempty"`
	TagIds           []string                 `json:"tag_ids,omitempty"`
	AudioIds         []string                 `json:"audio_ids,omitempty"`
	PerformerIds     []string                 `json:"performer_ids,omitempty"`
	ContainingGroups []*GroupDescriptionInput `json:"containing_groups,omitempty"`
	SubGroups        []*GroupDescriptionInput `json:"sub_groups,omitempty"`
	// This should be a URL or a base64 encoded data URL
	FrontImage *string `json:"front_image,omitempty"`
	// This should be a URL or a base64 encoded data URL
	BackImage    *string        `json:"back_image,omitempty"`
	CustomFields map[string]any `json:"custom_fields,omitempty"`
}

// GroupDescription represents a relationship to a group with a description of the relationship
type GroupDescription struct {
	Group       *models.Group `json:"group"`
	Description *string       `json:"description,omitempty"`
}

type GroupDescriptionInput struct {
	GroupID     string  `json:"group_id"`
	Description *string `json:"description,omitempty"`
}

type GroupDestroyInput struct {
	ID string `json:"id"`
}

type GroupSubGroupAddInput struct {
	ContainingGroupID string                   `json:"containing_group_id"`
	SubGroups         []*GroupDescriptionInput `json:"sub_groups"`
	// The index at which to insert the sub groups. If not provided, the sub groups will be appended to the end
	InsertIndex *int `json:"insert_index,omitempty"`
}

type GroupSubGroupRemoveInput struct {
	ContainingGroupID string   `json:"containing_group_id"`
	SubGroupIds       []string `json:"sub_group_ids"`
}

type GroupUpdateInput struct {
	ID               string                   `json:"id"`
	Name             *string                  `json:"name,omitempty"`
	Aliases          *string                  `json:"aliases,omitempty"`
	Duration         *int                     `json:"duration,omitempty"`
	Date             *string                  `json:"date,omitempty"`
	Rating100        *int                     `json:"rating100,omitempty"`
	StudioID         *string                  `json:"studio_id,omitempty"`
	Director         *string                  `json:"director,omitempty"`
	Synopsis         *string                  `json:"synopsis,omitempty"`
	Urls             []string                 `json:"urls,omitempty"`
	TagIds           []string                 `json:"tag_ids,omitempty"`
	AudioIds         []string                 `json:"audio_ids,omitempty"`
	PerformerIds     []string                 `json:"performer_ids,omitempty"`
	ContainingGroups []*GroupDescriptionInput `json:"containing_groups,omitempty"`
	SubGroups        []*GroupDescriptionInput `json:"sub_groups,omitempty"`
	// This should be a URL or a base64 encoded data URL
	FrontImage *string `json:"front_image,omitempty"`
	// This should be a URL or a base64 encoded data URL
	BackImage    *string                   `json:"back_image,omitempty"`
	CustomFields *models.CustomFieldsInput `json:"custom_fields,omitempty"`
}

type IdentifyFieldOptions struct {
	Field    string                `json:"field"`
	Strategy IdentifyFieldStrategy `json:"strategy"`
	// creates missing objects if needed - only applicable for performers, tags and studios
	CreateMissing *bool `json:"createMissing,omitempty"`
}

type IdentifyFieldOptionsInput struct {
	Field    string                `json:"field"`
	Strategy IdentifyFieldStrategy `json:"strategy"`
	// creates missing objects if needed - only applicable for performers, tags and studios
	CreateMissing *bool `json:"createMissing,omitempty"`
}

type IdentifyMetadataInput struct {
	// An ordered list of sources to identify items with. Only the first source that finds a match is used.
	Sources []*IdentifySourceInput `json:"sources"`
	// Options defined here override the configured defaults
	Options *IdentifyMetadataOptionsInput `json:"options,omitempty"`
	// scene ids to identify
	SceneIDs []string `json:"sceneIDs,omitempty"`
	// paths of scenes to identify - ignored if scene ids are set
	Paths []string `json:"paths,omitempty"`
}

type IdentifyMetadataOptions struct {
	// any fields missing from here are defaulted to MERGE and createMissing false
	FieldOptions []*IdentifyFieldOptions `json:"fieldOptions,omitempty"`
	// defaults to true if not provided
	SetCoverImage *bool `json:"setCoverImage,omitempty"`
	SetOrganized  *bool `json:"setOrganized,omitempty"`
	// defaults to true if not provided
	IncludeMalePerformers *bool `json:"includeMalePerformers,omitempty"`
	// Filter to only include performers with these genders. If not provided, all genders are included.
	PerformerGenders []models.GenderEnum `json:"performerGenders,omitempty"`
	// defaults to true if not provided
	SkipMultipleMatches *bool `json:"skipMultipleMatches,omitempty"`
	// tag to tag skipped multiple matches with
	SkipMultipleMatchTag *string `json:"skipMultipleMatchTag,omitempty"`
	// defaults to true if not provided
	SkipSingleNamePerformers *bool `json:"skipSingleNamePerformers,omitempty"`
	// tag to tag skipped single name performers with
	SkipSingleNamePerformerTag *string `json:"skipSingleNamePerformerTag,omitempty"`
}

type IdentifyMetadataOptionsInput struct {
	// any fields missing from here are defaulted to MERGE and createMissing false
	FieldOptions []*IdentifyFieldOptionsInput `json:"fieldOptions,omitempty"`
	// defaults to true if not provided
	SetCoverImage *bool `json:"setCoverImage,omitempty"`
	SetOrganized  *bool `json:"setOrganized,omitempty"`
	// defaults to true if not provided
	IncludeMalePerformers *bool `json:"includeMalePerformers,omitempty"`
	// Filter to only include performers with these genders. If not provided, all genders are included.
	PerformerGenders []models.GenderEnum `json:"performerGenders,omitempty"`
	// defaults to true if not provided
	SkipMultipleMatches *bool `json:"skipMultipleMatches,omitempty"`
	// tag to tag skipped multiple matches with
	SkipMultipleMatchTag *string `json:"skipMultipleMatchTag,omitempty"`
	// defaults to true if not provided
	SkipSingleNamePerformers *bool `json:"skipSingleNamePerformers,omitempty"`
	// tag to tag skipped single name performers with
	SkipSingleNamePerformerTag *string `json:"skipSingleNamePerformerTag,omitempty"`
}

type IdentifyMetadataTaskOptions struct {
	// An ordered list of sources to identify items with. Only the first source that finds a match is used.
	Sources []*IdentifySource `json:"sources"`
	// Options defined here override the configured defaults
	Options *IdentifyMetadataOptions `json:"options,omitempty"`
}

type IdentifySource struct {
	Source *ScraperSource `json:"source"`
	// Options defined for a source override the defaults
	Options *IdentifyMetadataOptions `json:"options,omitempty"`
}

type IdentifySourceInput struct {
	Source *ScraperSourceInput `json:"source"`
	// Options defined for a source override the defaults
	Options *IdentifyMetadataOptionsInput `json:"options,omitempty"`
}

type Job struct {
	ID          string     `json:"id"`
	Status      JobStatus  `json:"status"`
	SubTasks    []string   `json:"subTasks,omitempty"`
	Description string     `json:"description"`
	Progress    *float64   `json:"progress,omitempty"`
	StartTime   *time.Time `json:"startTime,omitempty"`
	EndTime     *time.Time `json:"endTime,omitempty"`
	AddTime     time.Time  `json:"addTime"`
	Error       *string    `json:"error,omitempty"`
}

type JobStatusUpdate struct {
	Type JobStatusUpdateType `json:"type"`
	Job  *Job                `json:"job"`
}

type LatestVersion struct {
	Version     string `json:"version"`
	Shorthash   string `json:"shorthash"`
	ReleaseDate string `json:"release_date"`
	URL         string `json:"url"`
}

type LogEntry struct {
	Time    time.Time `json:"time"`
	Level   LogLevel  `json:"level"`
	Message string    `json:"message"`
}

type MigrateBlobsInput struct {
	DeleteOld *bool `json:"deleteOld,omitempty"`
}

type MigrateSceneScreenshotsInput struct {
	DeleteFiles       *bool `json:"deleteFiles,omitempty"`
	OverwriteExisting *bool `json:"overwriteExisting,omitempty"`
}

type MoveFilesInput struct {
	Ids []string `json:"ids"`
	// valid for single or multiple file ids
	DestinationFolder *string `json:"destination_folder,omitempty"`
	// valid for single or multiple file ids
	DestinationFolderID *string `json:"destination_folder_id,omitempty"`
	// valid only for single file id. If empty, existing basename is used
	DestinationBasename *string `json:"destination_basename,omitempty"`
}

type MovieCreateInput struct {
	Name    string  `json:"name"`
	Aliases *string `json:"aliases,omitempty"`
	// Duration in seconds
	Duration  *int     `json:"duration,omitempty"`
	Date      *string  `json:"date,omitempty"`
	Rating100 *int     `json:"rating100,omitempty"`
	StudioID  *string  `json:"studio_id,omitempty"`
	Director  *string  `json:"director,omitempty"`
	Synopsis  *string  `json:"synopsis,omitempty"`
	URL       *string  `json:"url,omitempty"`
	Urls      []string `json:"urls,omitempty"`
	TagIds    []string `json:"tag_ids,omitempty"`
	// This should be a URL or a base64 encoded data URL
	FrontImage *string `json:"front_image,omitempty"`
	// This should be a URL or a base64 encoded data URL
	BackImage *string `json:"back_image,omitempty"`
}

type MovieDestroyInput struct {
	ID string `json:"id"`
}

type MovieUpdateInput struct {
	ID        string   `json:"id"`
	Name      *string  `json:"name,omitempty"`
	Aliases   *string  `json:"aliases,omitempty"`
	Duration  *int     `json:"duration,omitempty"`
	Date      *string  `json:"date,omitempty"`
	Rating100 *int     `json:"rating100,omitempty"`
	StudioID  *string  `json:"studio_id,omitempty"`
	Director  *string  `json:"director,omitempty"`
	Synopsis  *string  `json:"synopsis,omitempty"`
	URL       *string  `json:"url,omitempty"`
	Urls      []string `json:"urls,omitempty"`
	TagIds    []string `json:"tag_ids,omitempty"`
	// This should be a URL or a base64 encoded data URL
	FrontImage *string `json:"front_image,omitempty"`
	// This should be a URL or a base64 encoded data URL
	BackImage *string `json:"back_image,omitempty"`
}

type Mutation struct {
}

type Package struct {
	PackageID string     `json:"package_id"`
	Name      string     `json:"name"`
	Version   *string    `json:"version,omitempty"`
	Date      *time.Time `json:"date,omitempty"`
	Requires  []*Package `json:"requires"`
	SourceURL string     `json:"sourceURL"`
	// The version of this package currently available from the remote source
	SourcePackage *Package       `json:"source_package,omitempty"`
	Metadata      map[string]any `json:"metadata"`
}

type PackageSourceInput struct {
	Name      *string `json:"name,omitempty"`
	URL       string  `json:"url"`
	LocalPath *string `json:"local_path,omitempty"`
}

type PerformerDestroyInput struct {
	ID string `json:"id"`
}

type PerformerMergeInput struct {
	Source      []string                     `json:"source"`
	Destination string                       `json:"destination"`
	Values      *models.PerformerUpdateInput `json:"values,omitempty"`
}

type PluginPaths struct {
	Javascript []string `json:"javascript,omitempty"`
	CSS        []string `json:"css,omitempty"`
}

type PluginResult struct {
	Error  *string `json:"error,omitempty"`
	Result *string `json:"result,omitempty"`
}

// The query root for this schema
type Query struct {
}

type RemoveTempDLNAIPInput struct {
	Address string `json:"address"`
}

type ReorderSubGroupsInput struct {
	// ID of the group to reorder sub groups for
	GroupID string `json:"group_id"`
	// IDs of the sub groups to reorder. These must be a subset of the current sub groups.
	// Sub groups will be inserted in this order at the insert_index
	SubGroupIds []string `json:"sub_group_ids"`
	// The sub-group ID at which to insert the sub groups
	InsertAtID string `json:"insert_at_id"`
	// If true, the sub groups will be inserted after the insert_index, otherwise they will be inserted before
	InsertAfter *bool `json:"insert_after,omitempty"`
}

type SQLExecResult struct {
	// The number of rows affected by the query, usually an UPDATE, INSERT, or DELETE.
	// Not all queries or databases support this feature.
	RowsAffected *int64 `json:"rows_affected,omitempty"`
	// The integer generated by the database in response to a command.
	// Typically this will be from an "auto increment" column when inserting a new row.
	// Not all databases support this feature, and the syntax of such statements varies.
	LastInsertID *int64 `json:"last_insert_id,omitempty"`
}

type SQLQueryResult struct {
	// The column names, in the order they appear in the result set.
	Columns []string `json:"columns"`
	// The returned rows.
	Rows [][]any `json:"rows"`
}

type SaveFilterInput struct {
	// provide ID to overwrite existing filter
	ID           *string                `json:"id,omitempty"`
	Mode         models.FilterMode      `json:"mode"`
	Name         string                 `json:"name"`
	FindFilter   *models.FindFilterType `json:"find_filter,omitempty"`
	ObjectFilter map[string]any         `json:"object_filter,omitempty"`
	UIOptions    map[string]any         `json:"ui_options,omitempty"`
}

type ScrapeMultiPerformersInput struct {
	// Instructs to query by scene fingerprints
	PerformerIds []string `json:"performer_ids,omitempty"`
}

type ScrapeMultiScenesInput struct {
	// Instructs to query by scene fingerprints
	SceneIds []string `json:"scene_ids,omitempty"`
}

type ScrapeSingleGalleryInput struct {
	// Instructs to query by string
	Query *string `json:"query,omitempty"`
	// Instructs to query by gallery id
	GalleryID *string `json:"gallery_id,omitempty"`
	// Instructs to query by gallery fragment
	GalleryInput *ScrapedGalleryInput `json:"gallery_input,omitempty"`
}

type ScrapeSingleGroupInput struct {
	// Instructs to query by string
	Query *string `json:"query,omitempty"`
	// Instructs to query by group id
	GroupID *string `json:"group_id,omitempty"`
	// Instructs to query by group fragment
	GroupInput *ScrapedGroupInput `json:"group_input,omitempty"`
}

type ScrapeSingleImageInput struct {
	// Instructs to query by string
	Query *string `json:"query,omitempty"`
	// Instructs to query by image id
	ImageID *string `json:"image_id,omitempty"`
	// Instructs to query by image fragment
	ImageInput *ScrapedImageInput `json:"image_input,omitempty"`
}

type ScrapeSingleMovieInput struct {
	// Instructs to query by string
	Query *string `json:"query,omitempty"`
	// Instructs to query by movie id
	MovieID *string `json:"movie_id,omitempty"`
	// Instructs to query by movie fragment
	MovieInput *ScrapedMovieInput `json:"movie_input,omitempty"`
}

type ScrapeSinglePerformerInput struct {
	// Instructs to query by string
	Query *string `json:"query,omitempty"`
	// Instructs to query by performer id
	PerformerID *string `json:"performer_id,omitempty"`
	// Instructs to query by performer fragment
	PerformerInput *ScrapedPerformerInput `json:"performer_input,omitempty"`
}

type ScrapeSingleSceneInput struct {
	// Instructs to query by string
	Query *string `json:"query,omitempty"`
	// Instructs to query by scene fingerprints
	SceneID *string `json:"scene_id,omitempty"`
	// Instructs to query by scene fragment
	SceneInput *ScrapedSceneInput `json:"scene_input,omitempty"`
}

type ScrapeSingleStudioInput struct {
	// Query can be either a name or a Stash ID
	Query *string `json:"query,omitempty"`
}

type ScrapeSingleTagInput struct {
	// Query can be either a name or a Stash ID
	Query *string `json:"query,omitempty"`
}

type ScrapedGallery struct {
	Title        *string             `json:"title,omitempty"`
	Code         *string             `json:"code,omitempty"`
	Details      *string             `json:"details,omitempty"`
	Photographer *string             `json:"photographer,omitempty"`
	URL          *string             `json:"url,omitempty"`
	Urls         []string            `json:"urls,omitempty"`
	Date         *string             `json:"date,omitempty"`
	Studio       *ScrapedStudio      `json:"studio,omitempty"`
	Tags         []*ScrapedTag       `json:"tags,omitempty"`
	Performers   []*ScrapedPerformer `json:"performers,omitempty"`
}

func (ScrapedGallery) IsScrapedContent() {}

type ScrapedGalleryInput struct {
	Title        *string  `json:"title,omitempty"`
	Code         *string  `json:"code,omitempty"`
	Details      *string  `json:"details,omitempty"`
	Photographer *string  `json:"photographer,omitempty"`
	URL          *string  `json:"url,omitempty"`
	Urls         []string `json:"urls,omitempty"`
	Date         *string  `json:"date,omitempty"`
}

// A group from a scraping operation...
type ScrapedGroup struct {
	StoredID *string        `json:"stored_id,omitempty"`
	Name     *string        `json:"name,omitempty"`
	Aliases  *string        `json:"aliases,omitempty"`
	Duration *string        `json:"duration,omitempty"`
	Date     *string        `json:"date,omitempty"`
	Rating   *string        `json:"rating,omitempty"`
	Director *string        `json:"director,omitempty"`
	Urls     []string       `json:"urls,omitempty"`
	Synopsis *string        `json:"synopsis,omitempty"`
	Studio   *ScrapedStudio `json:"studio,omitempty"`
	Tags     []*ScrapedTag  `json:"tags,omitempty"`
	// This should be a base64 encoded data URL
	FrontImage *string `json:"front_image,omitempty"`
	// This should be a base64 encoded data URL
	BackImage *string `json:"back_image,omitempty"`
}

func (ScrapedGroup) IsScrapedContent() {}

type ScrapedGroupInput struct {
	Name     *string  `json:"name,omitempty"`
	Aliases  *string  `json:"aliases,omitempty"`
	Duration *string  `json:"duration,omitempty"`
	Date     *string  `json:"date,omitempty"`
	Rating   *string  `json:"rating,omitempty"`
	Director *string  `json:"director,omitempty"`
	Urls     []string `json:"urls,omitempty"`
	Synopsis *string  `json:"synopsis,omitempty"`
}

type ScrapedImage struct {
	Title        *string             `json:"title,omitempty"`
	Code         *string             `json:"code,omitempty"`
	Details      *string             `json:"details,omitempty"`
	Photographer *string             `json:"photographer,omitempty"`
	Urls         []string            `json:"urls,omitempty"`
	Date         *string             `json:"date,omitempty"`
	Studio       *ScrapedStudio      `json:"studio,omitempty"`
	Tags         []*ScrapedTag       `json:"tags,omitempty"`
	Performers   []*ScrapedPerformer `json:"performers,omitempty"`
}

func (ScrapedImage) IsScrapedContent() {}

type ScrapedImageInput struct {
	Title   *string  `json:"title,omitempty"`
	Code    *string  `json:"code,omitempty"`
	Details *string  `json:"details,omitempty"`
	Urls    []string `json:"urls,omitempty"`
	Date    *string  `json:"date,omitempty"`
}

// A movie from a scraping operation...
type ScrapedMovie struct {
	StoredID *string        `json:"stored_id,omitempty"`
	Name     *string        `json:"name,omitempty"`
	Aliases  *string        `json:"aliases,omitempty"`
	Duration *string        `json:"duration,omitempty"`
	Date     *string        `json:"date,omitempty"`
	Rating   *string        `json:"rating,omitempty"`
	Director *string        `json:"director,omitempty"`
	URL      *string        `json:"url,omitempty"`
	Urls     []string       `json:"urls,omitempty"`
	Synopsis *string        `json:"synopsis,omitempty"`
	Studio   *ScrapedStudio `json:"studio,omitempty"`
	Tags     []*ScrapedTag  `json:"tags,omitempty"`
	// This should be a base64 encoded data URL
	FrontImage *string `json:"front_image,omitempty"`
	// This should be a base64 encoded data URL
	BackImage *string `json:"back_image,omitempty"`
}

func (ScrapedMovie) IsScrapedContent() {}

type ScrapedMovieInput struct {
	Name     *string  `json:"name,omitempty"`
	Aliases  *string  `json:"aliases,omitempty"`
	Duration *string  `json:"duration,omitempty"`
	Date     *string  `json:"date,omitempty"`
	Rating   *string  `json:"rating,omitempty"`
	Director *string  `json:"director,omitempty"`
	URL      *string  `json:"url,omitempty"`
	Urls     []string `json:"urls,omitempty"`
	Synopsis *string  `json:"synopsis,omitempty"`
}

// A performer from a scraping operation...
type ScrapedPerformer struct {
	// Set if performer matched
	StoredID       *string       `json:"stored_id,omitempty"`
	Name           *string       `json:"name,omitempty"`
	Disambiguation *string       `json:"disambiguation,omitempty"`
	Gender         *string       `json:"gender,omitempty"`
	URL            *string       `json:"url,omitempty"`
	Urls           []string      `json:"urls,omitempty"`
	Twitter        *string       `json:"twitter,omitempty"`
	Instagram      *string       `json:"instagram,omitempty"`
	Birthdate      *string       `json:"birthdate,omitempty"`
	Ethnicity      *string       `json:"ethnicity,omitempty"`
	Country        *string       `json:"country,omitempty"`
	EyeColor       *string       `json:"eye_color,omitempty"`
	Height         *string       `json:"height,omitempty"`
	Measurements   *string       `json:"measurements,omitempty"`
	FakeTits       *string       `json:"fake_tits,omitempty"`
	PenisLength    *string       `json:"penis_length,omitempty"`
	Circumcised    *string       `json:"circumcised,omitempty"`
	CareerLength   *string       `json:"career_length,omitempty"`
	CareerStart    *int          `json:"career_start,omitempty"`
	CareerEnd      *int          `json:"career_end,omitempty"`
	Tattoos        *string       `json:"tattoos,omitempty"`
	Piercings      *string       `json:"piercings,omitempty"`
	Aliases        *string       `json:"aliases,omitempty"`
	Tags           []*ScrapedTag `json:"tags,omitempty"`
	// This should be a base64 encoded data URL
	Image        *string  `json:"image,omitempty"`
	Images       []string `json:"images,omitempty"`
	Details      *string  `json:"details,omitempty"`
	DeathDate    *string  `json:"death_date,omitempty"`
	HairColor    *string  `json:"hair_color,omitempty"`
	Weight       *string  `json:"weight,omitempty"`
	RemoteSiteID *string  `json:"remote_site_id,omitempty"`
}

func (ScrapedPerformer) IsScrapedContent() {}

type ScrapedPerformerInput struct {
	// Set if performer matched
	StoredID       *string  `json:"stored_id,omitempty"`
	Name           *string  `json:"name,omitempty"`
	Disambiguation *string  `json:"disambiguation,omitempty"`
	Gender         *string  `json:"gender,omitempty"`
	URL            *string  `json:"url,omitempty"`
	Urls           []string `json:"urls,omitempty"`
	Twitter        *string  `json:"twitter,omitempty"`
	Instagram      *string  `json:"instagram,omitempty"`
	Birthdate      *string  `json:"birthdate,omitempty"`
	Ethnicity      *string  `json:"ethnicity,omitempty"`
	Country        *string  `json:"country,omitempty"`
	EyeColor       *string  `json:"eye_color,omitempty"`
	Height         *string  `json:"height,omitempty"`
	Measurements   *string  `json:"measurements,omitempty"`
	FakeTits       *string  `json:"fake_tits,omitempty"`
	PenisLength    *string  `json:"penis_length,omitempty"`
	Circumcised    *string  `json:"circumcised,omitempty"`
	CareerLength   *string  `json:"career_length,omitempty"`
	CareerStart    *int     `json:"career_start,omitempty"`
	CareerEnd      *int     `json:"career_end,omitempty"`
	Tattoos        *string  `json:"tattoos,omitempty"`
	Piercings      *string  `json:"piercings,omitempty"`
	Aliases        *string  `json:"aliases,omitempty"`
	Details        *string  `json:"details,omitempty"`
	DeathDate      *string  `json:"death_date,omitempty"`
	HairColor      *string  `json:"hair_color,omitempty"`
	Weight         *string  `json:"weight,omitempty"`
	RemoteSiteID   *string  `json:"remote_site_id,omitempty"`
}

type ScrapedScene struct {
	Title    *string  `json:"title,omitempty"`
	Code     *string  `json:"code,omitempty"`
	Details  *string  `json:"details,omitempty"`
	Director *string  `json:"director,omitempty"`
	URL      *string  `json:"url,omitempty"`
	Urls     []string `json:"urls,omitempty"`
	Date     *string  `json:"date,omitempty"`
	// This should be a base64 encoded data URL
	Image        *string                       `json:"image,omitempty"`
	Studio       *ScrapedStudio                `json:"studio,omitempty"`
	Tags         []*ScrapedTag                 `json:"tags,omitempty"`
	Performers   []*ScrapedPerformer           `json:"performers,omitempty"`
	Movies       []*ScrapedMovie               `json:"movies,omitempty"`
	Groups       []*ScrapedGroup               `json:"groups,omitempty"`
	RemoteSiteID *string                       `json:"remote_site_id,omitempty"`
	Duration     *int                          `json:"duration,omitempty"`
	Fingerprints []*models.StashBoxFingerprint `json:"fingerprints,omitempty"`
}

func (ScrapedScene) IsScrapedContent() {}

type ScrapedSceneInput struct {
	Title        *string  `json:"title,omitempty"`
	Code         *string  `json:"code,omitempty"`
	Details      *string  `json:"details,omitempty"`
	Director     *string  `json:"director,omitempty"`
	URL          *string  `json:"url,omitempty"`
	Urls         []string `json:"urls,omitempty"`
	Date         *string  `json:"date,omitempty"`
	RemoteSiteID *string  `json:"remote_site_id,omitempty"`
}

type ScrapedStudio struct {
	// Set if studio matched
	StoredID *string        `json:"stored_id,omitempty"`
	Name     string         `json:"name"`
	URL      *string        `json:"url,omitempty"`
	Urls     []string       `json:"urls,omitempty"`
	Parent   *ScrapedStudio `json:"parent,omitempty"`
	Image    *string        `json:"image,omitempty"`
	Details  *string        `json:"details,omitempty"`
	// Aliases must be comma-delimited to be parsed correctly
	Aliases      *string       `json:"aliases,omitempty"`
	Tags         []*ScrapedTag `json:"tags,omitempty"`
	RemoteSiteID *string       `json:"remote_site_id,omitempty"`
}

func (ScrapedStudio) IsScrapedContent() {}

type ScrapedTag struct {
	// Set if tag matched
	StoredID    *string  `json:"stored_id,omitempty"`
	Name        string   `json:"name"`
	Description *string  `json:"description,omitempty"`
	AliasList   []string `json:"alias_list,omitempty"`
	// Remote site ID, if applicable
	RemoteSiteID *string `json:"remote_site_id,omitempty"`
}

func (ScrapedTag) IsScrapedContent() {}

type Scraper struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	// Details for performer scraper
	Performer *ScraperSpec `json:"performer,omitempty"`
	// Details for scene scraper
	Scene *ScraperSpec `json:"scene,omitempty"`
	// Details for gallery scraper
	Gallery *ScraperSpec `json:"gallery,omitempty"`
	// Details for image scraper
	Image *ScraperSpec `json:"image,omitempty"`
	// Details for movie scraper
	Movie *ScraperSpec `json:"movie,omitempty"`
	// Details for group scraper
	Group *ScraperSpec `json:"group,omitempty"`
}

type ScraperSource struct {
	// Index of the configured stash-box instance to use. Should be unset if scraper_id is set
	StashBoxIndex *int `json:"stash_box_index,omitempty"`
	// Stash-box endpoint
	StashBoxEndpoint *string `json:"stash_box_endpoint,omitempty"`
	// Scraper ID to scrape with. Should be unset if stash_box_endpoint/stash_box_index is set
	ScraperID *string `json:"scraper_id,omitempty"`
}

type ScraperSourceInput struct {
	// Index of the configured stash-box instance to use. Should be unset if scraper_id is set
	StashBoxIndex *int `json:"stash_box_index,omitempty"`
	// Stash-box endpoint
	StashBoxEndpoint *string `json:"stash_box_endpoint,omitempty"`
	// Scraper ID to scrape with. Should be unset if stash_box_endpoint/stash_box_index is set
	ScraperID *string `json:"scraper_id,omitempty"`
}

type ScraperSpec struct {
	// URLs matching these can be scraped with
	Urls             []string     `json:"urls,omitempty"`
	SupportedScrapes []ScrapeType `json:"supported_scrapes"`
}

type SetDefaultFilterInput struct {
	Mode models.FilterMode `json:"mode"`
	// null to clear
	FindFilter   *models.FindFilterType `json:"find_filter,omitempty"`
	ObjectFilter map[string]any         `json:"object_filter,omitempty"`
	UIOptions    map[string]any         `json:"ui_options,omitempty"`
}

type SetFingerprintsInput struct {
	Type string `json:"type"`
	// an null value will remove the fingerprint
	Value *string `json:"value,omitempty"`
}

// Accepts either ids, or a combination of names and stash_ids.
// If none are set, then all existing items will be tagged.
type StashBoxBatchTagInput struct {
	// Stash endpoint to use for the tagging
	Endpoint *int `json:"endpoint,omitempty"`
	// Endpoint of the stash-box instance to use
	StashBoxEndpoint *string `json:"stash_box_endpoint,omitempty"`
	// Fields to exclude when executing the tagging
	ExcludeFields []string `json:"exclude_fields,omitempty"`
	// Refresh items already tagged by StashBox if true. Only tag items with no StashBox tagging if false
	Refresh bool `json:"refresh"`
	// If batch adding studios, should their parent studios also be created?
	CreateParent bool `json:"createParent"`
	// IDs in stash of the items to update.
	// If set, names and stash_ids fields will be ignored.
	Ids []string `json:"ids,omitempty"`
	// Names of the items in the stash-box instance to search for and create
	Names []string `json:"names,omitempty"`
	// Stash IDs of the items in the stash-box instance to search for and create
	StashIds []string `json:"stash_ids,omitempty"`
	// IDs in stash of the performers to update
	PerformerIds []string `json:"performer_ids,omitempty"`
	// Names of the performers in the stash-box instance to search for and create
	PerformerNames []string `json:"performer_names,omitempty"`
}

type StashBoxDraftSubmissionInput struct {
	ID               string  `json:"id"`
	StashBoxIndex    *int    `json:"stash_box_index,omitempty"`
	StashBoxEndpoint *string `json:"stash_box_endpoint,omitempty"`
}

type StashBoxFingerprintSubmissionInput struct {
	SceneIds         []string `json:"scene_ids"`
	StashBoxIndex    *int     `json:"stash_box_index,omitempty"`
	StashBoxEndpoint *string  `json:"stash_box_endpoint,omitempty"`
}

type StashBoxPerformerQueryInput struct {
	// Index of the configured stash-box instance to use
	StashBoxIndex *int `json:"stash_box_index,omitempty"`
	// Endpoint of the stash-box instance to use
	StashBoxEndpoint *string `json:"stash_box_endpoint,omitempty"`
	// Instructs query by scene fingerprints
	PerformerIds []string `json:"performer_ids,omitempty"`
	// Query by query string
	Q *string `json:"q,omitempty"`
}

type StashBoxPerformerQueryResult struct {
	Query   string              `json:"query"`
	Results []*ScrapedPerformer `json:"results"`
}

type StashBoxSceneQueryInput struct {
	// Index of the configured stash-box instance to use
	StashBoxIndex *int `json:"stash_box_index,omitempty"`
	// Endpoint of the stash-box instance to use
	StashBoxEndpoint *string `json:"stash_box_endpoint,omitempty"`
	// Instructs query by scene fingerprints
	SceneIds []string `json:"scene_ids,omitempty"`
	// Query by query string
	Q *string `json:"q,omitempty"`
}

type StashBoxValidationResult struct {
	Valid  bool   `json:"valid"`
	Status string `json:"status"`
}

type StatsResultType struct {
	AudioCount     int     `json:"audio_count"`
	AudiosSize     float64 `json:"audios_size"`
	AudiosDuration float64 `json:"audios_duration"`
	PerformerCount int     `json:"performer_count"`
	StudioCount    int     `json:"studio_count"`
	GroupCount     int     `json:"group_count"`
	MovieCount     int     `json:"movie_count"`
	TagCount       int     `json:"tag_count"`
}

type StudioDestroyInput struct {
	ID string `json:"id"`
}

type Subscription struct {
}

type TagCreateInput struct {
	Name string `json:"name"`
	// Value that does not appear in the UI but overrides name for sorting
	SortName    *string `json:"sort_name,omitempty"`
	Description *string `json:"description,omitempty"`
	// Duplicate aliases and those equal to name will be ignored (case-insensitive)
	Aliases       []string `json:"aliases,omitempty"`
	IgnoreAutoTag *bool    `json:"ignore_auto_tag,omitempty"`
	Favorite      *bool    `json:"favorite,omitempty"`
	// This should be a URL or a base64 encoded data URL
	Image        *string                `json:"image,omitempty"`
	StashIds     []*models.StashIDInput `json:"stash_ids,omitempty"`
	ParentIds    []string               `json:"parent_ids,omitempty"`
	ChildIds     []string               `json:"child_ids,omitempty"`
	CustomFields map[string]any         `json:"custom_fields,omitempty"`
}

type TagDestroyInput struct {
	ID string `json:"id"`
}

type TagUpdateInput struct {
	ID   string  `json:"id"`
	Name *string `json:"name,omitempty"`
	// Value that does not appear in the UI but overrides name for sorting
	SortName    *string `json:"sort_name,omitempty"`
	Description *string `json:"description,omitempty"`
	// Duplicate aliases and those equal to name will be ignored (case-insensitive)
	Aliases       []string `json:"aliases,omitempty"`
	IgnoreAutoTag *bool    `json:"ignore_auto_tag,omitempty"`
	Favorite      *bool    `json:"favorite,omitempty"`
	// This should be a URL or a base64 encoded data URL
	Image        *string                   `json:"image,omitempty"`
	StashIds     []*models.StashIDInput    `json:"stash_ids,omitempty"`
	ParentIds    []string                  `json:"parent_ids,omitempty"`
	ChildIds     []string                  `json:"child_ids,omitempty"`
	CustomFields *models.CustomFieldsInput `json:"custom_fields,omitempty"`
}

type TagsMergeInput struct {
	Source      []string        `json:"source"`
	Destination string          `json:"destination"`
	Values      *TagUpdateInput `json:"values,omitempty"`
}

type Version struct {
	Version   *string `json:"version,omitempty"`
	Hash      string  `json:"hash"`
	BuildTime string  `json:"build_time"`
}

type IdentifyFieldStrategy string

const (
	// Never sets the field value
	IdentifyFieldStrategyIgnore IdentifyFieldStrategy = "IGNORE"
	// For multi-value fields, merge with existing.
	// For single-value fields, ignore if already set
	IdentifyFieldStrategyMerge IdentifyFieldStrategy = "MERGE"
	// Always replaces the value if a value is found.
	// For multi-value fields, any existing values are removed and replaced with the
	// scraped values.
	IdentifyFieldStrategyOverwrite IdentifyFieldStrategy = "OVERWRITE"
)

var AllIdentifyFieldStrategy = []IdentifyFieldStrategy{
	IdentifyFieldStrategyIgnore,
	IdentifyFieldStrategyMerge,
	IdentifyFieldStrategyOverwrite,
}

func (e IdentifyFieldStrategy) IsValid() bool {
	switch e {
	case IdentifyFieldStrategyIgnore, IdentifyFieldStrategyMerge, IdentifyFieldStrategyOverwrite:
		return true
	}
	return false
}

func (e IdentifyFieldStrategy) String() string {
	return string(e)
}

func (e *IdentifyFieldStrategy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = IdentifyFieldStrategy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid IdentifyFieldStrategy", str)
	}
	return nil
}

func (e IdentifyFieldStrategy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *IdentifyFieldStrategy) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e IdentifyFieldStrategy) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type JobStatus string

const (
	JobStatusReady     JobStatus = "READY"
	JobStatusRunning   JobStatus = "RUNNING"
	JobStatusFinished  JobStatus = "FINISHED"
	JobStatusStopping  JobStatus = "STOPPING"
	JobStatusCancelled JobStatus = "CANCELLED"
	JobStatusFailed    JobStatus = "FAILED"
)

var AllJobStatus = []JobStatus{
	JobStatusReady,
	JobStatusRunning,
	JobStatusFinished,
	JobStatusStopping,
	JobStatusCancelled,
	JobStatusFailed,
}

func (e JobStatus) IsValid() bool {
	switch e {
	case JobStatusReady, JobStatusRunning, JobStatusFinished, JobStatusStopping, JobStatusCancelled, JobStatusFailed:
		return true
	}
	return false
}

func (e JobStatus) String() string {
	return string(e)
}

func (e *JobStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = JobStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid JobStatus", str)
	}
	return nil
}

func (e JobStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *JobStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e JobStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type JobStatusUpdateType string

const (
	JobStatusUpdateTypeAdd    JobStatusUpdateType = "ADD"
	JobStatusUpdateTypeRemove JobStatusUpdateType = "REMOVE"
	JobStatusUpdateTypeUpdate JobStatusUpdateType = "UPDATE"
)

var AllJobStatusUpdateType = []JobStatusUpdateType{
	JobStatusUpdateTypeAdd,
	JobStatusUpdateTypeRemove,
	JobStatusUpdateTypeUpdate,
}

func (e JobStatusUpdateType) IsValid() bool {
	switch e {
	case JobStatusUpdateTypeAdd, JobStatusUpdateTypeRemove, JobStatusUpdateTypeUpdate:
		return true
	}
	return false
}

func (e JobStatusUpdateType) String() string {
	return string(e)
}

func (e *JobStatusUpdateType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = JobStatusUpdateType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid JobStatusUpdateType", str)
	}
	return nil
}

func (e JobStatusUpdateType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *JobStatusUpdateType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e JobStatusUpdateType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type LogLevel string

const (
	LogLevelTrace    LogLevel = "Trace"
	LogLevelDebug    LogLevel = "Debug"
	LogLevelInfo     LogLevel = "Info"
	LogLevelProgress LogLevel = "Progress"
	LogLevelWarning  LogLevel = "Warning"
	LogLevelError    LogLevel = "Error"
)

var AllLogLevel = []LogLevel{
	LogLevelTrace,
	LogLevelDebug,
	LogLevelInfo,
	LogLevelProgress,
	LogLevelWarning,
	LogLevelError,
}

func (e LogLevel) IsValid() bool {
	switch e {
	case LogLevelTrace, LogLevelDebug, LogLevelInfo, LogLevelProgress, LogLevelWarning, LogLevelError:
		return true
	}
	return false
}

func (e LogLevel) String() string {
	return string(e)
}

func (e *LogLevel) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LogLevel(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LogLevel", str)
	}
	return nil
}

func (e LogLevel) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LogLevel) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LogLevel) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PackageType string

const (
	PackageTypeScraper PackageType = "Scraper"
	PackageTypePlugin  PackageType = "Plugin"
)

var AllPackageType = []PackageType{
	PackageTypeScraper,
	PackageTypePlugin,
}

func (e PackageType) IsValid() bool {
	switch e {
	case PackageTypeScraper, PackageTypePlugin:
		return true
	}
	return false
}

func (e PackageType) String() string {
	return string(e)
}

func (e *PackageType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PackageType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PackageType", str)
	}
	return nil
}

func (e PackageType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PackageType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PackageType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Type of the content a scraper generates
type ScrapeContentType string

const (
	ScrapeContentTypeGallery   ScrapeContentType = "GALLERY"
	ScrapeContentTypeImage     ScrapeContentType = "IMAGE"
	ScrapeContentTypeMovie     ScrapeContentType = "MOVIE"
	ScrapeContentTypeGroup     ScrapeContentType = "GROUP"
	ScrapeContentTypePerformer ScrapeContentType = "PERFORMER"
	ScrapeContentTypeScene     ScrapeContentType = "SCENE"
)

var AllScrapeContentType = []ScrapeContentType{
	ScrapeContentTypeGallery,
	ScrapeContentTypeImage,
	ScrapeContentTypeMovie,
	ScrapeContentTypeGroup,
	ScrapeContentTypePerformer,
	ScrapeContentTypeScene,
}

func (e ScrapeContentType) IsValid() bool {
	switch e {
	case ScrapeContentTypeGallery, ScrapeContentTypeImage, ScrapeContentTypeMovie, ScrapeContentTypeGroup, ScrapeContentTypePerformer, ScrapeContentTypeScene:
		return true
	}
	return false
}

func (e ScrapeContentType) String() string {
	return string(e)
}

func (e *ScrapeContentType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ScrapeContentType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ScrapeContentType", str)
	}
	return nil
}

func (e ScrapeContentType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ScrapeContentType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ScrapeContentType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ScrapeType string

const (
	// From text query
	ScrapeTypeName ScrapeType = "NAME"
	// From existing object
	ScrapeTypeFragment ScrapeType = "FRAGMENT"
	// From URL
	ScrapeTypeURL ScrapeType = "URL"
)

var AllScrapeType = []ScrapeType{
	ScrapeTypeName,
	ScrapeTypeFragment,
	ScrapeTypeURL,
}

func (e ScrapeType) IsValid() bool {
	switch e {
	case ScrapeTypeName, ScrapeTypeFragment, ScrapeTypeURL:
		return true
	}
	return false
}

func (e ScrapeType) String() string {
	return string(e)
}

func (e *ScrapeType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ScrapeType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ScrapeType", str)
	}
	return nil
}

func (e ScrapeType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ScrapeType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ScrapeType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
